In [ ]:
import pandas as pd

In [ ]:
list_a = ['a', 'b', 'c']

In [ ]:
print(list_a)

['a', 'b', 'c']

In [ ]:
url = 'https://raw.githubusercontent.com/stefanbund/py3100/main/matrix.csv'

In [ ]:
ulta_df = pd.read_csv(url)

In [ ]:
ulta_df

,City,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,Birmingham,8285,5343,6738,6635,5658,8118,4311,8535,3436,...,1340,6923,3082,5617,3555,1341,1756,7598,1509,1861
1,Montgomery,1287,6585,8300,8874,8208,5363,3552,3387,2765,...,4424,8813,6655,3986,2805,4601,4449,5727,2315,8822
2,Mobile,8035,5569,9492,5905,5024,1107,6937,5580,8044,...,5430,1601,9145,1493,9807,2652,9296,2815,4886,7458
3,Huntsville,6280,2841,3399,5448,6173,5451,7488,9981,5236,...,9169,7829,6879,4166,7935,2605,9982,3338,9116,3875
4,Tuscaloosa,4079,1066,3923,4177,4277,4219,9436,8160,4302,...,1556,5533,1884,2088,3657,2158,4469,2513,8135,6963
5,Hoover,9741,7377,9410,9790,8864,2522,5347,9145,8402,...,6031,7673,8403,7588,9748,7224,4628,8107,6143,1671
6,Dothan,7646,2060,4911,4976,7851,4277,7423,6183,6641,...,8253,1565,6052,5802,5650,4400,7842,4006,9335,3571
7,Auburn,4326,2659,6928,4656,1828,5199,5331,6294,3076,...,6128,3737,7785,3281,4387,6890,2833,5083,9707,2116
8,Decatur,3786,2891,8124,2469,3704,3623,2409,8287,2032,...,6622,9742,9382,8413,9305,6509,6848,5408,3707,8744
9,Madison,1934,3628,9190,3275,9344,5778,1256,3523,1781,...,6619,6128,5325,9976,1746,4470,7054,6573,3556,1374
10,Florence,8017,3187,1128,4706,9962,7547,4440,4530,9569,...,8306,1392,1363,5545,5929,1123,7306,8746,4000,6943
11,Gadsden,2290,6402,8598,7547,5158,9731,8038,4435,7357,...,4488,3591,1683,7343,2549,5175,5997,9608,7230,9731
12,Vestavia Hills,9471,9142,4419,3846,2016,5069,4853,6336,9062,...,4613,2942,7408,9484,5142,9619,9601,8099,1391,6276
13,Prattville,6039,8003,6180,4610,3548,7115,6720,8512,9954,...,8225,7278,7358,2997,1591,4401,3457,4245,4341,2573
14,Phenix City,8788,8269,6838,2863,6753,6608,4048,8774,4513,...,5704,8720,3386,1295,3520,7654,6845,7738,3828,1202
15,Alabaster,1733,9767,3274,7125,7437,5748,5399,6513,3038,...,7351,9503,1081,7704,2479,9673,7478,7207,7006,3523
16,Bessemer,6559,2453,1578,5158,3058,8075,7066,8530,8346,...,8921,3517,4121,5295,4810,7641,5365,3545,6812,9483
17,Enterprise,8436,7800,7234,5063,4274,1948,7887,6647,1320,...,4840,6309,7334,9880,3461,2640,4375,8634,4917,2830
18,Opelika,9998,8953,7923,6176,4369,9503,2126,1816,9224,...,3217,1170,9351,1453,5191,9304,2720,3100,3912,1548
19,Homewood,2373,7188,9880,9236,5969,9998,8703,8440,4643,...,8144,8091,3869,4259,8787,5459,8389,5242,2224,6025
20,Northport,3536,9231,8651,6374,4842,5704,8484,6322,2012,...,2154,8484,1742,8443,6947,5401,6681,9018,1668,8307
21,Pelham,6830,3736,2734,6443,8494,6206,7290,8518,6176,...,9219,4891,4276,4976,2777,4045,7309,4745,4284,2640
22,Trussville,2794,8273,9174,2850,8351,3978,5995,4632,7693,...,2582,9365,8305,2147,1650,9470,6356,4700,3344,8743
23,Mountain Brook,8433,9368,2141,2357,6566,1482,4787,3900,6615,...,4666,9227,2858,2083,5765,3653,5198,9266,4945,3935
24,Fairhope,8114,1464,2811,3090,4686,7995,7676,1304,7332,...,4911,3255,2347,5816,3457,4808,7227,5482,6355,4553

In [ ]:
ulta_df['City']

0         Birmingham
1         Montgomery
2             Mobile
3         Huntsville
4         Tuscaloosa
5             Hoover
6             Dothan
7             Auburn
8            Decatur
9            Madison
10          Florence
11           Gadsden
12    Vestavia Hills
13        Prattville
14       Phenix City
15         Alabaster
16          Bessemer
17        Enterprise
18           Opelika
19          Homewood
20         Northport
21            Pelham
22        Trussville
23    Mountain Brook
24          Fairhope
Name: City, dtype: object